name: music-ai
channels: 
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - librosa
  - keras
  - tensorflow
  - rise
  - pip:
    - essentia
    - pretty_midi
    - pyfluidsynth
    - -e git://github.com/davidkant/mai#egg=mai